[project]
name = "stacklyzer"
version = "0.1.0"
description = "Simple Substack statistics."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "dateparser>=1.2.1",
    "pandas>=2.3.0",
    "streamlit>=1.45.1",
]
